// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtuisnshyhlymzigpkrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0dWlzbnNoeWhseW16aWdwa3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODY3NDEsImV4cCI6MjA2NDQ2Mjc0MX0.9eEpk453Ixgl69lyYp7l1lma0fTgP0O4M71aVnvXIEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});